School.Portal/Models/ErrorViewModel.cs
using System;

namespace School.Portal.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

School.Portal/Controllers/ClassRoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using School.Domain.Dto;
using School.Domain.Dto.Parameters;
using School.Domain.Interfaces.BusinessInterfaces;
using School.Domain.Interfaces.DtoInterfaces;

namespace School.Portal.Controllers
{
    public class ClassRoomController : Controller
    {
        private readonly IClassRoomBusiness _classRoomBusiness;
        private readonly ILevelBusiness _levelBusiness;
        public ClassRoomController(IClassRoomBusiness classRoomBusiness,ILevelBusiness levelBusiness)
        {
            _classRoomBusiness = classRoomBusiness;
            _levelBusiness = levelBusiness;
        }

        public async Task<IActionResult> Index()
        {
            var classRooms = await _classRoomBusiness.GetAllClassRooms();
            return View(classRooms);
        }

        public async Task<IActionResult> Create()
        {
            await GetLevelsDropDownList();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ClassRoomParameter parameter)
        {
            if (ModelState.IsValid)
            {
                var isAdded = await _classRoomBusiness.AddClassRoom(parameter);
                if (isAdded) return RedirectToAction("Index");
            }

            return View(parameter);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var classRoom = await _classRoomBusiness.GetClassRoom(id);
            await GetLevelsDropDownList(classRoom.LevelId);
            return View(classRoom);
        }

        private async Task GetLevelsDropDownList(int levelId = -1)
        {
            var levels = await _levelBusiness.GetAllLevels();
            List<SelectListItem> listItems = new List<SelectListItem>();
            foreach (var levelDto in levels)
            {
                var item = new SelectListItem
                {
                    Text = levelDto.LevelName,
                    Value = levelDto.LevelId.ToString(),
                    Selected = levelDto.LevelId == levelId
                };
                listItems.Add(item);
            }

            ViewBag.Levels = listItems;
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ClassRoomDto parameter)
        {
            if (ModelState.IsValid)
            {
                var isUpdated = await _classRoomBusiness.UpdateClassRoom(parameter);
                if (isUpdated) return RedirectToAction("Index");
            }

            return View(parameter);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _classRoomBusiness.DeleteClassRoom(id);
            return RedirectToAction("Index");
        }
    }
}

School.Portal/Controllers/GenderController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using School.Domain.Dto;
using School.Domain.Dto.Parameters;
using School.Domain.Interfaces.BusinessInterfaces;

namespace School.Portal.Controllers
{
    public class GenderController : Controller
    {
        private readonly IGenderBusiness _genderBusiness;

        public GenderController(IGenderBusiness genderBusiness)
        {
            _genderBusiness = genderBusiness;
        }
        public async Task<IActionResult> Index()
        {
            var result = await _genderBusiness.GetAllGenders();
            return View(result);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(GenderParameter parameter)
        {
            if (ModelState.IsValid)
            {
                var isAdded = await _genderBusiness.AddGender(parameter);
                if (isAdded)
                {
                    return RedirectToAction("Index");
                }
            }

            return View(parameter);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var gender = await _genderBusiness.GetGender(id);
            return View(gender);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(GenderDto parameter)
        {
            if (ModelState.IsValid)
            {
                var isUpdated = await _genderBusiness.UpdateGender(parameter);
                if (isUpdated)
                {
                    return RedirectToAction("Index");
                }
            }

            return View(parameter);
        }

        public async Task<IActionResult> Details(int id)
        {
            var gender = await _genderBusiness.GetGender(id);
            return View(gender);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var gender = await _genderBusiness.GetGender(id);
            return View(gender);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(GenderDto genderDto)
        {
            await _genderBusiness.DeleteGender(genderDto.GenderId);
            return RedirectToAction("Index");
        }
    }
}

School.Portal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using School.Portal.Models;

namespace School.Portal.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

School.Portal/Controllers/LevelController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using School.Domain.Dto;
using School.Domain.Dto.Parameters;
using School.Domain.Interfaces.BusinessInterfaces;
using School.Domain.Interfaces.DtoInterfaces;

namespace School.Portal.Controllers
{
    public class LevelController : Controller
    {
        private readonly ILevelBusiness _levelBusiness;

        public LevelController(ILevelBusiness levelBusiness)
        {
            _levelBusiness = levelBusiness;
        }

        public async Task<IActionResult> GetAllLevels()
        {
            var levels = await _levelBusiness.GetAllLevels();
            return View("Index", levels);
        }

        public async Task<IActionResult> AddOrUpdate(int? id)
        {
            ILevelDto level = new LevelDto();
            if (id != null)
            {
                level = await _levelBusiness.GetLevel(Convert.ToInt32(id));
            }
            return View(level);
        }

        [HttpPost]
        public async Task<IActionResult> AddOrUpdate(LevelDto levelDto)
        {
            if (levelDto.LevelId > 0)
                await _levelBusiness.UpdateLevel(levelDto);
            else
            {
                var levelParameter = new LevelParameter {LevelName = levelDto.LevelName};
                await _levelBusiness.AddLevel(levelParameter);
            }
            return RedirectToAction("GetAllLevels");
        }

        public async Task<IActionResult> Remove(int id)
        {
            await _levelBusiness.DeleteLevel(id);
            return RedirectToAction("GetAllLevels");
        }
    }
}

School.Portal/Views/ClassRoom/Create.cshtml
@model ClassRoomParameter

@{
    ViewData["Title"] = "Create";
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClassRoomName" class="control-label"></label>
                <input asp-for="ClassRoomName" class="form-control" />
                <span asp-validation-for="ClassRoomName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LevelId" class="control-label"></label>
                @*<input asp-for="LevelId" class="form-control" />*@
                @Html.DropDownListFor(model=>model.LevelId, ViewBag.Levels as List<SelectListItem>,"-- Select Level --",new {@class = "form-control" })
                <span asp-validation-for="LevelId" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

School.Portal/Views/ClassRoom/Edit.cshtml
@model IClassRoomDto

@{
    ViewData["Title"] = "Edit";
}


<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input asp-for="ClassRoomId" hidden="hidden" />
            
            <div class="form-group">
                <label asp-for="ClassRoomName" class="control-label"></label>
                <input asp-for="ClassRoomName" class="form-control" />
                <span asp-validation-for="ClassRoomName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LevelId" class="control-label"></label>
                @Html.DropDownListFor(model=>model.LevelId,ViewBag.Levels as List<SelectListItem>,"-- Select --",new{ @class = "form-control" })
                <span asp-validation-for="LevelId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

School.Portal/Views/ClassRoom/Index.cshtml
@model IEnumerable<IClassRoomDto>

@{
    ViewData["Title"] = "Index";
}

<p>
    <a asp-action="Create" class="btn btn-success">Create</a>
</p>
<table class="table table-active">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ClassRoomName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LevelName)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ClassRoomName)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.LevelName)
            </td>
            <td>
                <a class="btn btn-info" asp-action="Edit" asp-route-id="@item.ClassRoomId">Edit</a>
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.ClassRoomId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

School.Portal/Views/Gender/Create.cshtml
@model GenderParameter

@{
    ViewData["Title"] = "Create";
}


<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GenderType" class="control-label"></label>
                <input asp-for="GenderType" class="form-control" />
                <span asp-validation-for="GenderType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

School.Portal/Views/Gender/Delete.cshtml
@model IGenderDto

@{
    ViewData["Title"] = "Delete";
}

<h3>Are you sure you want to delete this?</h3>
<div>
   
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GenderId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GenderId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GenderType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GenderType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input hidden="hidden" asp-for="GenderId" />
        <input hidden="hidden" asp-for="GenderType" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

School.Portal/Views/Gender/Details.cshtml
@model School.Domain.Interfaces.DtoInterfaces.IGenderDto

@{
    ViewData["Title"] = "Details";
}



<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GenderId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GenderId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GenderType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GenderType)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.GenderId }) |
    <a asp-action="Index">Back to List</a>
</div>

School.Portal/Views/Gender/Edit.cshtml
@model School.Domain.Interfaces.DtoInterfaces.IGenderDto

@{
    ViewData["Title"] = "Edit";
}


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*@Html.HiddenFor(x => x.GenderId)*@
            <input hidden="hidden" asp-for="GenderId" />
            <div class="form-group">
                <label asp-for="GenderType" class="control-label"></label>
                <input asp-for="GenderType" class="form-control" />
                <span asp-validation-for="GenderType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

School.Portal/Views/Gender/Index.cshtml
@model IEnumerable<IGenderDto>

@{
    ViewData["Title"] = "Index";
}



<p>
    <a class="btn btn-success" asp-action="Create">Create New</a>
</p>
<table class="table table-active">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GenderType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GenderType)
            </td>
            <td>
                <a class="btn btn-info" asp-action="Edit" asp-route-id="@item.GenderId">Edit</a>
                <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.GenderId">Details</a>
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.GenderId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

School.Portal/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

School.Portal/Views/Level/AddOrUpdate.cshtml
@model ILevelDto

@{
    ViewData["Title"] = "AddOrUpdate";
}

<h1>
    @if (Model.LevelId > 0)
    {
        <span>Update</span>
    }
    else
    {
        <span>Create</span>
    }
</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddOrUpdate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(model => model.LevelId)
            <div class="form-group">
                <label asp-for="LevelName" class="control-label"></label>
                <input asp-for="LevelName" class="form-control" />
                <span asp-validation-for="LevelName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="GetAllLevels">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

School.Portal/Views/Level/Index.cshtml
@model IEnumerable<ILevelDto>

@{
    ViewData["Title"] = "Index";
}


<p>
    <a class="btn btn-success" asp-action="AddOrUpdate">Create New</a>
</p>
<table class="table table-active">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LevelName)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LevelName)
            </td>
            <td>
                <a class="btn btn-info" asp-action="AddOrUpdate" asp-route-id="@item.LevelId">Update</a>
                <a class="btn btn-danger" asp-action="Remove" asp-route-id="@item.LevelId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

School.Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - School.Portal</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">School.Portal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gender" asp-action="Index">Gender</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Level" asp-action="GetAllLevels">Level</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ClassRoom" asp-action="Index">Classes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - School.Portal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>